In [1]:
import pandas as pd
import numpy as np
import sqlite3

### Loading in the most backed projects data from kickstarter

In [3]:
most_backed = pd.read_csv('most_backed.csv')
most_backed.head()

,Unnamed: 0,amt.pledged,blurb,by,category,currency,goal,location,num.backers,num.backers.tier,pledge.tier,title,url
0,0,8782571.0,\nThis is a card game for people who are into ...,Elan Lee,Tabletop Games,usd,10000.0,"Los Angeles, CA",219382,"[15505, 202934, 200, 5]","[20.0, 35.0, 100.0, 500.0]",Exploding Kittens,/projects/elanlee/exploding-kittens
1,1,6465690.0,"\nAn unusually addicting, high-quality desk to...",Matthew and Mark McLachlan,Product Design,usd,15000.0,"Denver, CO",154926,"[788, 250, 43073, 21796, 41727, 21627, 12215, ...","[1.0, 14.0, 19.0, 19.0, 35.0, 35.0, 79.0, 79.0...",Fidget Cube: A Vinyl Desk Toy,/projects/antsylabs/fidget-cube-a-vinyl-desk-toy
2,2,5408916.0,\nBring Reading Rainbow’s library of interacti...,LeVar Burton & Reading Rainbow,Web,usd,1000000.0,"Los Angeles, CA",105857,"[19639, 14343, 9136, 2259, 5666, 24512, 4957, ...","[5.0, 10.0, 25.0, 30.0, 35.0, 50.0, 75.0, 100....","Bring Reading Rainbow Back for Every Child, Ev...",/projects/readingrainbow/bring-reading-rainbow...
3,3,5702153.0,\nUPDATED: This is it. We're making a Veronica...,Rob Thomas,Narrative Film,usd,2000000.0,"San Diego, CA",91585,"[5938, 8423, 11509, 22997, 23227, 1865, 7260, ...","[1.0, 10.0, 25.0, 35.0, 50.0, 75.0, 100.0, 150...",The Veronica Mars Movie Project,/projects/559914737/the-veronica-mars-movie-pr...
4,4,3336371.0,"\nAn adventure game from Tim Schafer, Double F...",Double Fine and 2 Player Productions,Video Games,usd,400000.0,"San Francisco, CA",87142,"[47946, 24636, 1090, 11530, 900, 148, 100, 10, 4]","[15.0, 30.0, 60.0, 100.0, 250.0, 500.0, 1000.0...",Double Fine Adventure,/projects/doublefine/double-fine-adventure

# Auditing accuracy
In the data shown above, we see the 5 most backed projects on kickstater. We can see that the data holds true by going to kickstarters website and listing the most backed projects on their site.
https://www.kickstarter.com/discover/advanced?woe_id=23424977&sort=most_backed&seed=2528755&page=3

# Auditing completeness

Comparing column metrics of our dataset with a similar Kickstarter project dataset on Kaggle, we find a few columns missing in our dataset as well as a few extra columns of information compared to the dataset found at https://www.kaggle.com/kemical/kickstarter-projects/data
The column metadata of the said dataset is as shown below:

<img src = 'kickstarter.png'>

#### Comparing these column attributes to the attributes of our dataset:

In [252]:
most_backed.columns

Index(['Project ID', 'Amount Pledged', 'Blurb', 'Inventor ID', 'Category ID',
       'Currency', 'Goal', 'Location', 'No. Backers', 'Title', 'URL'],
      dtype='object')

#### The attributes missing in our dataset are: <br>
1 A subcategory column in addition to the category column <br>
2 The launch data and end date of the project <br>
3 State of the project (Success or failure)<br>
<br>
#### The extra attributes in our dataset are: <br>
1 Information on the various tiers a backer can pledge (20, 40, 60 etc) on a specific project <br>
2 The number of backers for each pledge tier <br>
3 URL of each project <br>
4 Blurb for each project <br>
5 The name of the creator for each project <br>
Overall we can say that our dataset is more complete and analaysis-ready than other datasets found on kaggle. <br>

# Auditing consistency/uniformity

In [5]:
most_backed.describe()

        Unnamed: 0   amt.pledged          goal    num.backers
count  4000.000000  4.000000e+03  4.000000e+03    4000.000000
mean   1999.500000  2.899923e+05  6.175203e+04    3582.875750
std    1154.844867  7.119369e+05  1.266715e+05    7316.102809
min       0.000000  1.925000e+03  1.000000e+00    1109.000000
25%     999.750000  6.771300e+04  1.300000e+04    1406.750000
50%    1999.500000  1.205860e+05  3.000000e+04    1946.000000
75%    2999.250000  2.593680e+05  6.000000e+04    3372.000000
max    3999.000000  2.033899e+07  2.000000e+06  219382.000000

In [7]:
most_backed.isnull().sum()

Unnamed: 0          0
amt.pledged         0
blurb               0
by                  0
category            0
currency            0
goal                0
location            0
num.backers         0
num.backers.tier    0
pledge.tier         0
title               0
url                 0
dtype: int64

### We see that there are no null values in our dataset. Our dataset appears to be pre-cleaned and ready for analysis. We also see that the data appears to be consistent throughout the rows and the possibility of outliers in the dataset is low.

In [8]:
conn = sqlite3.connect('kickstarter_prokects.db')

In [10]:
most_backed.to_sql('most_backed',conn, index = False, if_exists='replace')

C:\Users\hashe\Anaconda3\lib\site-packages\pandas\core\generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [18]:
def run_query(query):
    return pd.read_sql(query,conn)

In [19]:
most_backed.head()

,Unnamed: 0,amt.pledged,blurb,by,category,currency,goal,location,num.backers,num.backers.tier,pledge.tier,title,url
0,0,8782571.0,\nThis is a card game for people who are into ...,Elan Lee,Tabletop Games,usd,10000.0,"Los Angeles, CA",219382,"[15505, 202934, 200, 5]","[20.0, 35.0, 100.0, 500.0]",Exploding Kittens,/projects/elanlee/exploding-kittens
1,1,6465690.0,"\nAn unusually addicting, high-quality desk to...",Matthew and Mark McLachlan,Product Design,usd,15000.0,"Denver, CO",154926,"[788, 250, 43073, 21796, 41727, 21627, 12215, ...","[1.0, 14.0, 19.0, 19.0, 35.0, 35.0, 79.0, 79.0...",Fidget Cube: A Vinyl Desk Toy,/projects/antsylabs/fidget-cube-a-vinyl-desk-toy
2,2,5408916.0,\nBring Reading Rainbow’s library of interacti...,LeVar Burton & Reading Rainbow,Web,usd,1000000.0,"Los Angeles, CA",105857,"[19639, 14343, 9136, 2259, 5666, 24512, 4957, ...","[5.0, 10.0, 25.0, 30.0, 35.0, 50.0, 75.0, 100....","Bring Reading Rainbow Back for Every Child, Ev...",/projects/readingrainbow/bring-reading-rainbow...
3,3,5702153.0,\nUPDATED: This is it. We're making a Veronica...,Rob Thomas,Narrative Film,usd,2000000.0,"San Diego, CA",91585,"[5938, 8423, 11509, 22997, 23227, 1865, 7260, ...","[1.0, 10.0, 25.0, 35.0, 50.0, 75.0, 100.0, 150...",The Veronica Mars Movie Project,/projects/559914737/the-veronica-mars-movie-pr...
4,4,3336371.0,"\nAn adventure game from Tim Schafer, Double F...",Double Fine and 2 Player Productions,Video Games,usd,400000.0,"San Francisco, CA",87142,"[47946, 24636, 1090, 11530, 900, 148, 100, 10, 4]","[15.0, 30.0, 60.0, 100.0, 250.0, 500.0, 1000.0...",Double Fine Adventure,/projects/doublefine/double-fine-adventure

#### Creating a list of the pledge tiers and its associated backers

In [20]:
pledge_list=[]
for string in most_backed['pledge.tier']:
    ind_lis=[]
    string = string.replace('[','').replace(']','').replace(' ...','').split(',')
    for strin in string:
        if strin != '':
            ind_lis.append(float(strin))
    pledge_list.append(ind_lis)

In [21]:
backers_list=[]
for string in most_backed['num.backers.tier']:
    ind_lis=[]
    string = string.replace('[','').replace(']','').replace(' ...','').split(',')
    for strin in string:
        if strin != '':
            ind_lis.append(float(strin))
    backers_list.append(ind_lis)

### Creating a dataframe of the pledge tiers and backers. 
(I have split the process into 4 parts each as Jupyter notebook seems to run into problems when consolidating all 4000 rows at once)

In [59]:
frames=[]
for each in pledge_list[:1000]:
    df = pd.DataFrame(each, columns = ['Pledge Tiers'])
    frames.append(df)
    pledge_df_1= pd.concat(frames)

In [61]:
frames=[]
for each in pledge_list[1000:2000]:
    df = pd.DataFrame(each, columns = ['Pledge Tiers'])
    frames.append(df)
    pledge_df_2= pd.concat(frames)

In [66]:
frames=[]
for each in pledge_list[2000:3000]:
    df = pd.DataFrame(each, columns = ['Pledge Tiers'])
    frames.append(df)
    pledge_df_3= pd.concat(frames)

In [63]:
frames=[]
for each in pledge_list[3000:]:
    df = pd.DataFrame(each, columns = ['Pledge Tiers'])
    frames.append(df)
    pledge_df_4= pd.concat(frames)

In [69]:
pledge_df = pd.concat([pledge_df_1, pledge_df_2, pledge_df_3, pledge_df_4])

In [70]:
pledge_df.shape

(57990, 1)

In [95]:
frames=[]
for each in backers_list[:1000]:
    df = pd.DataFrame(each, columns = ['Backers'])
    frames.append(df)
    backers_df_1= pd.concat(frames)

In [97]:
frames=[]
for each in backers_list[1000:2000]:
    df = pd.DataFrame(each, columns = ['Backers'])
    frames.append(df)
    backers_df_2= pd.concat(frames)

In [99]:
frames=[]
for each in backers_list[2000:3000]:
    df = pd.DataFrame(each, columns = ['Backers'])
    frames.append(df)
    backers_df_3= pd.concat(frames)

In [101]:
frames=[]
for each in backers_list[3000:4000]:
    df = pd.DataFrame(each, columns = ['Backers'])
    frames.append(df)
    backers_df_4= pd.concat(frames)

In [103]:
backers_df = pd.concat([backers_df_1,backers_df_2,backers_df_3,backers_df_4])

In [104]:
backers_df.shape

(57990, 1)

In [123]:
pledge_tiers_df = pd.concat([pledge_df, backers_df], axis = 1)

In [143]:
pledge_tiers_df = pledge_tiers_df[['Pledge Tiers', 'Backers']]
pledge_tiers_df['Pledge ID'] = 1
pledge_tiers_df.reset_index(drop=True, inplace = True)

In [144]:
count = 0
for i, value in enumerate(pledge_list):
    for each in value:
        pledge_tiers_df.loc[count, 'Pledge ID'] = i
        count+=1

In [145]:
pledge_tiers_df = pledge_tiers_df[['Pledge ID', 'Pledge Tiers', 'Backers']]
pledge_tiers_df.head()

   Pledge ID  Pledge Tiers   Backers
0          0          20.0   15505.0
1          0          35.0  202934.0
2          0         100.0     200.0
3          0         500.0       5.0
4          1           1.0     788.0

In [146]:
pledge_tiers_df.to_sql('Pledge_Tiers',conn,index= False, if_exists = 'replace')

C:\Users\hashe\Anaconda3\lib\site-packages\pandas\core\generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [150]:
run_query('select name from sqlite_master where type = "table"')

           name
0   most_backed
1  Pledge_Tiers

In [173]:
inventor_list = list(set(most_backed_df['by']))
inventor_list[1514]

'LeVar Burton & Reading Rainbow'

In [202]:
most_backed.columns = ['Project ID', 'Amount Pledged', 'Blurb', 'Inventor ID', 'Category ID', 'Currency', 'Goal', 'Location', 'No. Backers', 'Tier', 'P tier', 'Title', 'URL']

In [187]:
category_list = list(set(most_backed_df['category']))
category_list[101]

'Product Design'

In [183]:
for i, value in enumerate(most_backed['category']):
    for a, val in enumerate(category_list):
        if value == val:
            most_backed.loc[i,'category'] = a

In [208]:
most_backed = most_backed[['Project ID', 'Amount Pledged', 'Blurb', 'Inventor ID', 'Category ID', 'Currency', 'Goal', 'Location', 'No. Backers', 'Title', 'URL']]

In [209]:
most_backed

,Project ID,Amount Pledged,Blurb,Inventor ID,Category ID,Currency,Goal,Location,No. Backers,Title,URL
0,0,8782571.0,\nThis is a card game for people who are into ...,930,112,usd,10000.0,"Los Angeles, CA",219382,Exploding Kittens,/projects/elanlee/exploding-kittens
1,1,6465690.0,"\nAn unusually addicting, high-quality desk to...",92,101,usd,15000.0,"Denver, CO",154926,Fidget Cube: A Vinyl Desk Toy,/projects/antsylabs/fidget-cube-a-vinyl-desk-toy
2,2,5408916.0,\nBring Reading Rainbow’s library of interacti...,1514,64,usd,1000000.0,"Los Angeles, CA",105857,"Bring Reading Rainbow Back for Every Child, Ev...",/projects/readingrainbow/bring-reading-rainbow...
3,3,5702153.0,\nUPDATED: This is it. We're making a Veronica...,1928,78,usd,2000000.0,"San Diego, CA",91585,The Veronica Mars Movie Project,/projects/559914737/the-veronica-mars-movie-pr...
4,4,3336371.0,"\nAn adventure game from Tim Schafer, Double F...",627,47,usd,400000.0,"San Francisco, CA",87142,Double Fine Adventure,/projects/doublefine/double-fine-adventure
5,5,20338986.0,\nColor e-paper smartwatch with up to 7 days o...,1709,101,usd,500000.0,"Palo Alto, CA",78471,"Pebble Time - Awesome Smartwatch, No Compromises",/projects/597507018/pebble-time-awesome-smartw...
6,6,4188927.0,\nA story-driven CRPG set in the world of Mont...,2916,47,usd,900000.0,"Newport Beach, CA",74405,Torment: Tides of Numenera,/projects/inxile/torment-tides-of-numenera
7,7,3986929.0,"\nPillars of Eternity is an isometric, party-b...",926,47,usd,1100000.0,"Irvine, CA",73986,Pillars of Eternity (formerly Project Eternity),/projects/obsidian/project-eternity
8,8,2090104.0,\nThe creative talent behind Banjo-Kazooie and...,562,47,gbp,175000.0,"Derby, UK",73206,Yooka-Laylee - A 3D Platformer Rare-vival!,/projects/playtonic/yooka-laylee-a-3d-platform...
9,9,3007370.0,\nZNAPS is a magnetic adapter specially design...,1730,26,cad,120000.0,"Toronto, Canada",70122,ZNAPS - Connection is just a snap away,/projects/1041610927/znaps-the-9-magnetic-adap...
10,10,6333295.0,\nYu Suzuki presents the long awaited third in...,2263,47,usd,2000000.0,"Tokyo, Japan",69320,Shenmue 3,/projects/ysnet/shenmue-3
11,11,10266845.0,\nPebble is a customizable watch. Download new...,1709,101,usd,100000.0,"Palo Alto, CA",68929,Pebble: E-Paper Watch for iPhone and Android,/projects/597507018/pebble-e-paper-watch-for-i...
12,12,3845170.0,"\nClassic Japanese side-scrolling action, evol...",237,47,usd,900000.0,"Tokyo, Japan",67226,Mighty No. 9,/projects/mightyno9/mighty-no-9
13,13,12779843.0,"\nTwo affordable, heart rate-enabled smartwatc...",1709,101,usd,1000000.0,"Redwood City, CA",66673,"Pebble 2, Time 2 + All-New Pebble Core",/projects/597507018/pebble-2-time-2-and-core-a...
14,14,5545991.0,"\nIGAVANIA (n): A gothic, exploration-focused ...",2548,47,usd,500000.0,"Tokyo, Japan",64867,Bloodstained: Ritual of the Night,/projects/iga/bloodstained-ritual-of-the-night
15,15,3246588.0,\nFrom the creators of Cyanide & Happiness com...,2992,112,usd,10000.0,"Dallas, TX",63758,Joking Hazard,/projects/cyanideandhappiness/joking-hazard
16,16,8596474.0,\nCracking open the last closed platform: the ...,821,3,usd,950000.0,"Los Angeles, CA",63416,OUYA: A New Kind of Video Game Console,/projects/ouya/ouya-a-new-kind-of-video-game-c...
17,17,13285226.0,\nThe COOLEST is a portable party disguised as...,162,101,usd,50000.0,"Portland, OR",62642,COOLEST COOLER: 21st Century Cooler that's Act...,/projects/ryangrepper/coolest-cooler-21st-cent...
18,18,2933252.0,\nWasteland 2 has been released to great accla...,2916,47,usd,900000.0,"Newport Beach, CA",61290,Wasteland 2,/projects/inxile/wasteland-2
19,19,5764229.0,\nYou did it: you brought back MYSTERY SCIENCE...,2863,49,usd,2000000.0,"Minneapolis, MN",48270,Bring Back MYSTERY SCIENCE THEATER 3000,/projects/mst3k/bringbackmst3k
20,20,3105473.0,"\n""Hell, there are no rules here - we're tryin...",2063,78,usd,2000000.0,"Los Angeles, CA",46520,WISH I WAS HERE,/projects/1869987317/wish-i-was-here-1
21,21,9192055.0,"\nTRAVEL JACKET with built-in Neck Pillow, Eye...",3089,101,usd,20000.0,"Chicago, IL",44949,The World's Best TRAVEL JACKET with 15 Feature...,/projects/597538543/the-worlds-best-travel-jac...
22,22,2229344.0,\nPlanetary Annihilation brings RTS gameplay t...,760,47,usd,900000.0,"Kirkland, WA",44162,Planetary Annihilation - A Next Generation RTS,/projects/659943965/planetary-annihilation-a-n...
23,23,2032434.0,"\nAn epic RPG with turn-based combat, cooperat...",755,47,usd,500000.0,"Sacramento, CA",42713,Divinity: Original Sin 2,/projects/larianstudios/divinity-original-sin-2
24,24,2785537.0,\nMissed the Kickstarter? Become a Late Reinfo...,2018,47,usd,250000.0,"Kirkland, WA",41733,BATTLETECH - Tactical 'Mech Combat Returns to ...,/projects/webeharebrained/battletech
25,25,2071927.0,"\nBuilt for work, play, and everything in betw...",789,0,usd,50000.0,"Oakland, CA",39560,CHIP - The World's First Nine Dollar Computer,/projects/1598272670/chip-the-worlds-first-9-c...
26,26,1731465.0,\nPINE A64 is the world's first 64-bit expanda...,2115,0,usd,31416.0,"San Francisco, CA",36781,"PINE A64, First $15 64-Bit Single Board Super ...",/projects/pine64/pine-a64-first-15-64-bit-sing...
27,27,1836447.0,\nShadowrun Returns brings back one of our mos...,2018,47,usd,400000.0,"Bellevue, WA",36276,Shadowrun Returns,/projects/webeharebrained/shadowrun-returns
28,28,1106371.0,\nRealistic single-player RPG set in the medie...,1389,47,gbp,300000.0,"Prague, Czech Republic",35384,Kingdom Come: Deliverance,/projects/1294225970/kingdom-come-deliverance
29,29,1479046.0,\nA social deduction game for 5-10 players abo...,1361,112,usd,54450.0,"Chicago, IL",34565,Secret Hitler,/projects/maxtemkin/secret-hitler
...,...,...,...,...,...,...,...,...,...,...,...
3970,3970,16692.0,\nWe're raising money to finance a self releas...,2881,20,gbp,10000.0,"Merthyr Tydfil, UK",1113,The Blackout: Wolves E.P.,/projects/1648679145/the-blackout-wolves-ep
3971,3971,100348.0,"\nFinally, an era of WW2 shipgirls dawns on ou...",2836,47,usd,30000.0,"San Diego, CA",1113,Victory Belles,/projects/blackchickenstudios/victory-belles
3972,3972,30303.0,"\nA game about communities by Ben Robbins, cre...",1235,112,usd,2500.0,"Seattle, WA",1113,Kingdom,/projects/lamemage/kingdom
3973,3973,122264.0,\nModernist design flair and roadside car cult...,1423,101,usd,50000.0,"Brooklyn, NY",1113,Midcentury Americana - Awesome Wood Toys,/projects/candylab/midcentury-americana-awesom...
3974,3974,105147.0,\nA thrilling stealth board game for two to fo...,1046,112,gbp,40000.0,"London, UK",1112,"Rise of the Kage, ninja board game with detail...",/projects/1207064031/rise-of-the-kage-ninja-bo...
3975,3975,155838.0,\nNow you can control your sprinklers with you...,2312,0,usd,75000.0,"American Fork, UT",1112,Lono Sprinkler Controller,/projects/173231925/lono-sprinkler-controller
3976,3976,378725.0,\nNorse playing cards designed in the heart of...,2376,110,dkk,85000.0,"Copenhagen, Denmark",1112,Midgard Playing Cards,/projects/653481781/midgard-playing-cards
3977,3977,42901.0,"\nLaser cut, etched & wrapped in leather, Kiki...",2813,101,usd,1000.0,"Wayland, MA",1112,Kiki: toolbox meets key ring!,/projects/onehundred/kiki-toolbox-meets-keyring
3978,3978,82811.0,\nToonbox Studio presents the great girls-artb...,252,42,usd,1000.0,"Omsk, Russia",1112,Artbook by Otto Schmidt,/projects/muntyan/artbook-by-otto-schmidt
3979,3979,51213.0,\nThe InterLock™ hides inside of your bike fra...,120,101,usd,48000.0,"Vancouver, Canada",1112,The InterLock\u2122 - The Lock that Hides Insi...,/projects/solgaarddesign/the-interlocktm-the-l...
3980,3980,91465.0,\nA biographical cookbook about culinary legen...,1015,43,usd,45000.0,"Berkeley, CA",1112,UNFORGETTABLE: Bold Flavors from a Renegade Life,/projects/265444901/unforgettable-bold-flavors...
3981,3981,31107.0,"\nMore than 400 monsters, obnoxious creatures,...",679,104,usd,10000.0,"Pittsburgh, PA",1111,BADbandanas\u2014100% cotton and 100% bad,/projects/159974695/badbandanas100-cotton-and-...
3982,3982,37622.0,"\nGrave is an open-world, surrealist survival ...",2939,47,usd,30000.0,"Phoenix, AZ",1111,Grave: Open World Survival Horror,/projects/2129301589/grave-open-world-survival...
3983,3983,82056.0,\nSchlock Mercenary:The Board Game is based on...,1845,112,usd,25000.0,"Houston, TX",1111,Schlock Mercenary The Board Game,/projects/1253203485/schlock-mercenary-the-boa...
3984,3984,108893.0,\nNisolo is a socially conscious lifestyle bra...,873,48,usd,35000.0,"Nairobi, Kenya",1111,Nisolo: Elegant Jewelry Handmade in Kenya,/projects/275883568/nisolo-elegant-jewelry-han...
3985,3985,40356.0,\nAn exciting class teaching you how to make i...,2311,45,usd,750.0,"Provo, UT",1111,How to Make a Freaking iPhone App - iOS 9 Adve...,/projects/1766493251/how-to-make-a-freaking-ip...
3986,3986,69829.0,"\nDesign and durability meet in a refillable, ...",955,101,usd,5000.0,"Portland, OR",1111,Bull & Stash Notebooks,/projects/678685617/bull-and-stash-notebooks
3987,3987,67767.0,"\nA minimalist brewer for ""making tea with ski...",846,101,usd,40000.0,"Chicago, IL",1111,Manual Tea Maker N\xba1,/projects/390812913/manual-tea-maker-no1
3988,3988,47450.0,\nChange the way crime is covered. Create a re...,1513,9,usd,40000.0,"Washington, DC",1110,A One Year Student Reporting Lab within Homici...,/projects/1368665357/a-one-year-student-report...
3989,3989,47321.0,\nSteal the most valuable items from the Museu...,1362,112,usd,15000.0,"Toledo, OH",1110,Master Thief,/projects/sparrgames/master-thief
3990,3990,17570.0,\nTo light the candle is to cast a shadow.\n,557,47,gbp,12000.0,"London, UK",1110,LUNA - The Shadow Dust: A Point and Click Puzz...,/projects/lanternstudio/luna-the-shadow-dust-a...
3991,3991,147396.0,"\nShoot fast, charge fast! Huge ammunition and...",2714,101,usd,5000.0,"Luhans'k, Ukraine",1110,Rubber Band Machine Gun with unique Fast Charger,/projects/11447722/rubber-band-machine-gun-0
3992,3992,145034.0,\nB-Squares is a 3D modular electronics system...,1251,0,usd,25000.0,"Seattle, WA",1110,B-Squares: Modular Solar Powered Electrics.,/projects/jmcrae/b-squares-modular-solar-power...
3993,3993,467167.0,"\nLight enough to carry anywhere, fast enough ...",904,101,usd,100000.0,"Palo Alto, CA",1110,Boosted Boards - The World's Lightest Electric...,/projects/170315130/boosted-boards-the-worlds-...
3994,3994,46982.0,\nWhat if you could tuck a lucky penny in the ...,825,87,usd,10000.0,"Oakland, CA",1109,Seed Money: Coins You Can Plant!,/projects/leafcutterdesigns/seed-money-coins-y...
3995,3995,93331.0,"\nBecome a monster to fight the monsters—""Rip""...",2697,112,usd,5000.0,"Chandler, AZ",1109,Savage Worlds: Rippers Resurrected RPG!,/projects/545820095/savage-worlds-rippers-resu...
3996,3996,186144.0,\nThe GoBone automatically entertains your dog...,2919,82,usd,60000.0,"Dallas, TX",1109,GoBone: The world's first smartbone,/projects/santiagogutierrez/gobone-all-day-pla...
3997,3997,60955.0,\nCreate and share better spherical panoramas ...,3,0,usd,20000.0,"Hong Kong, Hong Kong",1109,Orbit 360: A better way to take spherical pano...,/projects/imcardboard/orbit-360-a-better-way-t...
3998,3998,69452.0,\nThe Origins returned to the 16th century and...,625,52,nzd,40000.0,"Hamilton, NZ",1109,Origins Playing Cards - Printed by the USPCC,/projects/rickdavidson/origins-playing-cards-i...
3999,3999,24409.0,\n52 weeks. 52 artists. One illustrated year.\n,1609,42,gbp,10000.0,"London, UK",1109,Yellow: The Collected Book,/projects/1907907192/yellow-the-collected-book

In [226]:
inventor_df = pd.DataFrame(inventor_list, columns = ['Inventor'])
count = 0
for i,each in enumerate(inventor_df['Inventor']):
    inventor_df.loc[i,'Inventor ID'] = int(count)
    count+=1

In [229]:
inventor_df= inventor_df[['Inventor ID', 'Inventor']]
inventor_df.head()

   Inventor ID          Inventor
0          0.0   Two Tumbleweeds
1          1.0       Kill Screen
2          2.0     Katrina Spade
3          3.0    I AM Cardboard
4          4.0  John Szczepaniak

In [230]:
category_df = pd.DataFrame(category_list, columns = ['Category'])
count = 0
for i,each in enumerate(category_df['Category']):
    category_df.loc[i, 'Category ID'] = int(count)
    count+=1
category_df = category_df[['Category ID', 'Category']]
category_df.head()

   Category ID         Category
0          0.0         Hardware
1          1.0            Dance
2          2.0           Crafts
3          3.0  Gaming Hardware
4          4.0   Conceptual Art

In [254]:
inventor_df.to_sql('Inventor', conn, if_exists='replace', index=False )

C:\Users\hashe\Anaconda3\lib\site-packages\pandas\core\generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [232]:
category_df.to_sql('Category', conn, if_exists = 'replace', index=False)

C:\Users\hashe\Anaconda3\lib\site-packages\pandas\core\generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

## The tables in our database:

In [256]:
run_query('Select name from sqlite_master where type = "table"')

           name
0  Pledge_Tiers
1      Category
2   most_backed
3      Inventor

### We now have 4 tables in our 'kickstarter_prokects' database. Pledge tiers is a table with the various pledge tiers and its associated backers corresponding to each project. Category is a table containing the various categories that a project can fall under. Inventor is a table that contains the name of the creator/inventor for each project. The most_backed table consists of information for each of our kickstarter projects.

<img src = 'Table_Schema.png'>

# Let us now check whether each of our tables is in first normal form

(For the purpose of the use-cases clause of this assignment, i have created a separate table for inventor and category by creating artificial IDs for each category.)

In [257]:
run_query('Select * from most_backed limit 5')

,Project ID,Amount Pledged,Blurb,Inventor ID,Category ID,Currency,Goal,Location,No. Backers,Title,URL
0,0,8782571.0,\nThis is a card game for people who are into ...,930,112,usd,10000.0,"Los Angeles, CA",219382,Exploding Kittens,/projects/elanlee/exploding-kittens
1,1,6465690.0,"\nAn unusually addicting, high-quality desk to...",92,101,usd,15000.0,"Denver, CO",154926,Fidget Cube: A Vinyl Desk Toy,/projects/antsylabs/fidget-cube-a-vinyl-desk-toy
2,2,5408916.0,\nBring Reading Rainbow’s library of interacti...,1514,64,usd,1000000.0,"Los Angeles, CA",105857,"Bring Reading Rainbow Back for Every Child, Ev...",/projects/readingrainbow/bring-reading-rainbow...
3,3,5702153.0,\nUPDATED: This is it. We're making a Veronica...,1928,78,usd,2000000.0,"San Diego, CA",91585,The Veronica Mars Movie Project,/projects/559914737/the-veronica-mars-movie-pr...
4,4,3336371.0,"\nAn adventure game from Tim Schafer, Double F...",627,47,usd,400000.0,"San Francisco, CA",87142,Double Fine Adventure,/projects/doublefine/double-fine-adventure

This table seems to be in the first normal form as: <br>
1 There is a primary key ( Project ID) <br>
2 There are no repeating groups <br>
3 The values in each column of a table are atomic

In [263]:
run_query('select * from inventor limit 5')

   Inventor ID          Inventor
0          0.0   Two Tumbleweeds
1          1.0       Kill Screen
2          2.0     Katrina Spade
3          3.0    I AM Cardboard
4          4.0  John Szczepaniak

In [264]:
run_query('select * from category limit 5')

   Category ID         Category
0          0.0         Hardware
1          1.0            Dance
2          2.0           Crafts
3          3.0  Gaming Hardware
4          4.0   Conceptual Art

In [265]:
run_query('select * from pledge_tiers limit 5')

   Pledge ID  Pledge Tiers   Backers
0          0          20.0   15505.0
1          0          35.0  202934.0
2          0         100.0     200.0
3          0         500.0       5.0
4          1           1.0     788.0

### Each of our tables is in first normal form.

## Use-cases:

### 1. List all the projects that are in the games category

In [271]:
run_query('SELECT * FROM most_backed INNER JOIN category ON most_backed."Category ID" = category."Category ID" WHERE category.category LIKE "%Games%" ')

,Project ID,Amount Pledged,Blurb,Inventor ID,Category ID,Currency,Goal,Location,No. Backers,Title,URL,Category ID,Category
0,4,3336371.0,"\nAn adventure game from Tim Schafer, Double F...",627,47,usd,400000.0,"San Francisco, CA",87142,Double Fine Adventure,/projects/doublefine/double-fine-adventure,47.0,Video Games
1,6,4188927.0,\nA story-driven CRPG set in the world of Mont...,2916,47,usd,900000.0,"Newport Beach, CA",74405,Torment: Tides of Numenera,/projects/inxile/torment-tides-of-numenera,47.0,Video Games
2,7,3986929.0,"\nPillars of Eternity is an isometric, party-b...",926,47,usd,1100000.0,"Irvine, CA",73986,Pillars of Eternity (formerly Project Eternity),/projects/obsidian/project-eternity,47.0,Video Games
3,8,2090104.0,\nThe creative talent behind Banjo-Kazooie and...,562,47,gbp,175000.0,"Derby, UK",73206,Yooka-Laylee - A 3D Platformer Rare-vival!,/projects/playtonic/yooka-laylee-a-3d-platform...,47.0,Video Games
4,10,6333295.0,\nYu Suzuki presents the long awaited third in...,2263,47,usd,2000000.0,"Tokyo, Japan",69320,Shenmue 3,/projects/ysnet/shenmue-3,47.0,Video Games
5,12,3845170.0,"\nClassic Japanese side-scrolling action, evol...",237,47,usd,900000.0,"Tokyo, Japan",67226,Mighty No. 9,/projects/mightyno9/mighty-no-9,47.0,Video Games
6,14,5545991.0,"\nIGAVANIA (n): A gothic, exploration-focused ...",2548,47,usd,500000.0,"Tokyo, Japan",64867,Bloodstained: Ritual of the Night,/projects/iga/bloodstained-ritual-of-the-night,47.0,Video Games
7,18,2933252.0,\nWasteland 2 has been released to great accla...,2916,47,usd,900000.0,"Newport Beach, CA",61290,Wasteland 2,/projects/inxile/wasteland-2,47.0,Video Games
8,22,2229344.0,\nPlanetary Annihilation brings RTS gameplay t...,760,47,usd,900000.0,"Kirkland, WA",44162,Planetary Annihilation - A Next Generation RTS,/projects/659943965/planetary-annihilation-a-n...,47.0,Video Games
9,23,2032434.0,"\nAn epic RPG with turn-based combat, cooperat...",755,47,usd,500000.0,"Sacramento, CA",42713,Divinity: Original Sin 2,/projects/larianstudios/divinity-original-sin-2,47.0,Video Games
10,24,2785537.0,\nMissed the Kickstarter? Become a Late Reinfo...,2018,47,usd,250000.0,"Kirkland, WA",41733,BATTLETECH - Tactical 'Mech Combat Returns to ...,/projects/webeharebrained/battletech,47.0,Video Games
11,27,1836447.0,\nShadowrun Returns brings back one of our mos...,2018,47,usd,400000.0,"Bellevue, WA",36276,Shadowrun Returns,/projects/webeharebrained/shadowrun-returns,47.0,Video Games
12,28,1106371.0,\nRealistic single-player RPG set in the medie...,1389,47,gbp,300000.0,"Prague, Czech Republic",35384,Kingdom Come: Deliverance,/projects/1294225970/kingdom-come-deliverance,47.0,Video Games
13,30,2134374.0,\nReclaim the stars in the exciting new Space ...,571,47,usd,500000.0,"Los Angeles, CA",34397,Star Citizen,/projects/cig/star-citizen,47.0,Video Games
14,31,1519680.0,\nFrom the creators of Wasteland 2 and Torment...,2916,47,usd,1250000.0,"Newport Beach, CA",33741,The Bard's Tale IV,/projects/inxile/the-bards-tale-iv,47.0,Video Games
15,32,1229015.0,\nA tactical strategy game on an epic fantasy ...,627,47,usd,725000.0,"San Francisco, CA",31774,Double Fine's MASSIVE CHALICE,/projects/doublefine/double-fines-massive-chalice,47.0,Video Games
16,33,1204726.0,\nA Shadowrun cyberpunk cRPG set in 2056's Mag...,2018,47,usd,100000.0,"Kirkland, WA",31497,Shadowrun: Hong Kong,/projects/webeharebrained/shadowrun-hong-kong,47.0,Video Games
17,38,702516.0,\nCastle Story is a voxel-based creative strat...,384,47,usd,80000.0,"Montreal, Canada",27060,Castle Story,/projects/902505202/castle-story,47.0,Video Games
18,41,1578316.0,\nTake a ship and 100 credits to make money le...,3086,47,gbp,1250000.0,"Cambridge, UK",25681,Elite: Dangerous,/projects/1461411552/elite-dangerous,47.0,Video Games
19,43,2485506.0,"\nAn adventure game based on Homestuck, by And...",1474,47,usd,700000.0,"Miami, FL",24346,Homestuck Adventure Game,/projects/14293468/homestuck-adventure-game,47.0,Video Games
20,44,645158.0,"\nExplore a beautiful, vast and ruined world r...",1406,47,usd,27000.0,"Los Angeles, CA",24150,Hyper Light Drifter,/projects/1661802484/hyper-light-drifter,47.0,Video Games
21,48,751920.0,"\nA sandbox strategy game with town building, ...",30,47,usd,120000.0,"San Jose, CA",22844,Stonehearth,/projects/1590639245/stonehearth,47.0,Video Games
22,50,1919275.0,\nLord British returns to his fantasy RPG root...,1471,47,usd,1000000.0,"Austin, TX",22322,Shroud of the Avatar: Forsaken Virtues,/projects/portalarium/shroud-of-the-avatar-for...,47.0,Video Games
23,51,1321306.0,"\nAn all-new, immersive adventure game from th...",1908,47,usd,1100000.0,"Spokane, WA",22195,Obduction,/projects/cyaninc/obduction,47.0,Video Games
24,53,1538425.0,\nDreamfall Chapters is the long-awaited seque...,796,47,usd,850000.0,"Oslo, Norway",21858,Dreamfall Chapters: The Longest Journey,/projects/redthread/dreamfall-chapters-the-lon...,47.0,Video Games
25,55,1350700.0,\nSystem Shock is a complete remake of the gen...,2958,47,usd,900000.0,"Vancouver, WA",21625,System Shock,/projects/1598858095/system-shock,47.0,Video Games
26,61,723886.0,"\nA mature, story-driven, turn-based strategy ...",121,47,usd,100000.0,"Austin, TX",20042,The Banner Saga,/projects/stoic/the-banner-saga,47.0,Video Games
27,62,1578950.0,"\nTurn-based tactical combat for PC and Mac, s...",1402,47,usd,550000.0,"Bellevue, WA",19829,WARMACHINE: TACTICS,/projects/409030043/warmachine-tactics,47.0,Video Games
28,64,944282.0,\nDivinity Original Sin is an old-school cRPG ...,755,47,usd,400000.0,"Ghent, Belgium",19541,Divinity: Original Sin,/projects/larianstudios/divinity-original-sin,47.0,Video Games
29,67,776084.0,\nA Belly Dancing Hair-Whipping HD adventure f...,1352,47,usd,400000.0,"Los Angeles, CA",18558,Shantae: Half-Genie Hero,/projects/1236620800/shantae-half-genie-hero,47.0,Video Games
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274,977,101716.0,\nA classic puzzle filled adventure game retur...,1169,114,usd,50000.0,"Cambridge, MA",3424,Zoombinis,/projects/zoombinisgame/zoombinis,114.0,Games
1275,1208,108065.0,"\nTo buy online, click below:\n",860,114,usd,40000.0,"San Francisco, CA",2879,Yoga Joes: the classic green army men doing yoga,/projects/241445217/yoga-joes-army-men-doing-yoga,114.0,Games
1276,1387,72107.0,\nWelcome to Frog Fractions 2. You'll learn al...,2614,114,usd,60000.0,"Oakland, CA",2571,Frog Fractions 2,/projects/475057068/frog-fractions-2,114.0,Games
1277,1407,728985.0,\nDreadBall – The Futuristic Sports Game - fan...,1791,114,usd,20000.0,"Nottingham, UK",2539,DreadBall - The Futuristic Sports Game,/projects/1744629938/dreadball-the-futuristic-...,114.0,Games
1278,1459,82879.0,"\nTreasure-looting, monster-fighting, dungeon-...",2704,114,usd,4000.0,"Kirkland, WA",2455,Dungeon World: A Game with Modern Rules & Old-...,/projects/sage-kobold/dungeon-world-a-game-wit...,114.0,Games
1279,1708,93845.0,"\nHillfolk, a game of epic personal interactio...",879,114,usd,3000.0,"Toronto, Canada",2185,Hillfolk: DramaSystem roleplaying by Robin D. ...,/projects/robindlaws/hillfolk-dramasystem-role...,114.0,Games
1280,1786,380015.0,\nContribute to help give the Deluxe W20 Editi...,1807,114,usd,85000.0,"Macungie, PA",2108,Deluxe Werewolf the Apocalypse 20th Anniversar...,/projects/200664283/deluxe-werewolf-the-apocal...,114.0,Games
1281,2036,239955.0,"\nWith your help, we created the ultimate Mind...",2950,114,usd,60000.0,"New Orleans, LA",1921,Mind's Eye Theatre: Vampire The Masquerade,/projects/bynightstudios/minds-eye-theatre-vam...,114.0,Games
1282,2062,130447.0,\nEvery top is meticulously checked to ensure ...,2934,114,cad,1500.0,"Toronto, Canada",1899,ForeverSpin\u2122 Spinning Tops,/projects/1251371853/forever-spinning-top,114.0,Games
1283,2142,71179.0,\nSpriter is an animation tool for 2d games. L...,286,114,usd,25000.0,"Port Richey, FL",1844,Spriter,/projects/539087245/spriter,114.0,Games
1284,2161,100428.0,\nHow often do you wish you had Isiah Whitlock...,1862,114,usd,12500.0,"New York, NY",1828,"Isiah Whitlock, Jr. Talking Bobblehead",/projects/1556507886/isiah-whitlock-jr-talking...,114.0,Games
1285,2606,39651.0,"\nNimble & flexible, Roll20 brings the best of...",503,114,usd,5000.0,"Wichita, KS",1580,Roll20 -- Virtual tabletop gaming that tells a...,/projects/rileydutton/roll20-virtual-tabletop-...,114.0,Games
1286,2636,354997.0,"\nA fantasy tabletop game with simple, competi...",1791,114,usd,5000.0,"Nottingham, UK",1568,Kings of War,/projects/1744629938/kings-of-war,114.0,Games
1287,2669,62723.0,\ntremulus is a storytelling RPG where you and...,612,114,usd,5000.0,"Memphis, TN",1555,tremulus: a storytelling game of lovecraftian ...,/projects/1227949612/tremulus-a-storytelling-g...,114.0,Games
1288,2793,4773.0,\nIt's a $1 Roleplaying Game. Why are you look...,848,114,usd,1.0,"Issaquah, WA",1499,The $1 Play What You Want Mystery Campaign RPG...,/projects/218255739/the-1-play-what-you-want-m...,114.0,Games
1289,2899,49003.0,\nBADASS: Spades & Grenades. The only deck whe...,1927,114,usd,10000.0,"Seattle, WA",1449,BADASS: Spades & Grenades - Playing Cards with...,/projects/2146143533/badass-spades-and-grenade...,114.0,Games
1290,3003,78118.0,\nPrecision Machined Spinning Tops for the pro...,517,114,usd,3000.0,"Tucson, AZ",1405,Precision Machined Spinning Tops,/projects/124127689/precision-machined-spinnin...,114.0,Games
1291,3015,77471.0,\nThe best game magazine ever is getting best-...,1,114,usd,68000.0,"Brooklyn, NY",1399,The New Kill Screen Magazine,/projects/killscreen/help-kill-screen-reinvent...,114.0,Games
1292,3088,207804.0,\nA re-imagining of the iconic Horror on the O...,1743,114,usd,20000.0,"Hayward, CA",1374,Horror on the Orient Express: Call of Cthulhu ...,/projects/448333182/horror-on-the-orient-expre...,114.0,Games
1293,3103,66246.0,\nA gorgeous anthology of some of the most div...,1022,114,usd,30000.0,"Portland, OR",1370,The Offworld Collection,/projects/1315256652/the-offworld-collection,114.0,Games
1294,3205,109970.0,\nEarn badges and RPG level-ups for the books ...,239,114,usd,102364.0,"New York, NY",1327,The Game of Books: Reward Your Imagination,/projects/aaronstanton/the-game-of-books-a-dis...,114.0,Games
1295,3216,120263.0,\nAll we've heard for two years is that we nee...,220,114,usd,100000.0,"Dallas, TX",1323,Let's Throw The Best Gaming Party in The World...,/projects/screwattack/let-throw-the-best-gamin...,114.0,Games
1296,3231,233852.0,\nStop pretending sticks and cardboard tubes a...,1767,114,usd,50000.0,"Austin, TX",1318,Sabertron: Foam Swords with Electronic Scoring,/projects/levelup/sabertron-foam-swords-with-e...,114.0,Games
1297,3284,47746.0,\nA science fiction adventure comedy for adult...,1752,114,usd,20000.0,"Brooklyn, NY",1301,Trial of the Clone 2: Wrath of the Pacifist,/projects/weiner/trial-of-the-clone-2-wrath-of...,114.0,Games
1298,3547,30787.0,\nAn app that gets you playing the perfect gam...,564,114,gbp,25000.0,"London, UK",1226,"Tiny Games: Hundreds of real-world games, insi...",/projects/1755218595/tiny-games-hundreds-of-re...,114.0,Games
1299,3673,80608.0,\nPrecision machined playable dice in two diff...,517,114,usd,4000.0,"Tucson, AZ",1193,Precision Machined Metal Gaming Dice,/projects/124127689/precision-machined-metal-p...,114.0,Games
1300,3768,26040.0,\nCore Worlds Digital is based on the original...,2409,114,usd,20000.0,"Rochester, NY",1168,Core Worlds Digital,/projects/1468883172/core-worlds-digital,114.0,Games
1301,3854,50055.0,\nValence teaches kids advanced chemistry with...,1346,114,usd,12000.0,"Brooklyn, NY",1144,Science Ninjas: Valence --- Chemistry Card Game,/projects/natsch/science-ninjas-valence-chemis...,114.0,Games
1302,3863,117648.0,\nHard-boiled detective pen-and-paper roleplay...,2697,114,usd,8000.0,"Chandler, AZ",1140,Deadlands Noir,/projects/545820095/deadlands-noir,114.0,Games
1303,3893,96326.0,\nContribute to help give the V20 Companion th...,1807,114,usd,50000.0,"Macungie, PA",1134,V20 Companion Deluxe Edition,/projects/200664283/v20-companion-deluxe-edition,114.0,Games

We see that an overwhelming majority (1304 out of 4000) of the most backed projects on kickstarter are in the games category ! (This includes Video Games, Tabletop Games etc)

### List all the inventors from Texas

In [274]:
run_query('SELECT inventor.inventor, most_backed.location FROM most_backed INNER JOIN inventor ON most_backed."inventor id" = inventor."inventor id" WHERE most_backed.location LIKE "%TX"')

                            Inventor         Location
0              Cyanide And Happiness       Dallas, TX
1                      Rooster Teeth       Austin, TX
2                  Portalarium, Inc.       Austin, TX
3                 Tinnus Enterprises        Plano, TX
4                              Stoic       Austin, TX
5                  Reaper Miniatures       Denton, TX
6       ArtCraft Entertainment, Inc.       Austin, TX
7                  Reaper Miniatures       Denton, TX
8             Kris, Rob, Matt & Dave       Dallas, TX
9                  Airship Syndicate       Austin, TX
10                      Replay Games       Austin, TX
11   The Fun Pimps Entertainment LLC       Dallas, TX
12                 Reaper Miniatures       Denton, TX
13                     Albino Dragon       Austin, TX
14                   BlankMediaGames       Austin, TX
15                            Knocki      Houston, TX
16                Descendent Studios       Austin, TX
17                   BlankMediaGames       Austin, TX
18                     BSX Athletics       Austin, TX
19                    Zachary Weiner      Houston, TX
20               Steve Jackson Games       Austin, TX
21                    Skyshine Games       Austin, TX
22                    Zachary Weiner      Houston, TX
23                             Ngozi       Austin, TX
24                        Solo Stove   Fort Worth, TX
25        Dan Provost & Tom Gerhardt       Austin, TX
26                    don hertzfeldt       Austin, TX
27                    Sandy Petersen     Rockwall, TX
28                    Sandy Petersen     Rockwall, TX
29         HOT Smart Watch from PHTL       Dallas, TX
..                               ...              ...
124                       Fwoosh LLC  San Antonio, TX
125                 Jackson Robinson         Kyle, TX
126                      Queen Games       Dallas, TX
127                    Albino Dragon       Austin, TX
128                    Foxtrot Games       Dallas, TX
129                       B&A Studio      Houston, TX
130                    Cobblebot LLC      Houston, TX
131                       B&A Studio      Houston, TX
132                       Dann Kriss      Kountze, TX
133                 Bobby@Go7 Gaming       Austin, TX
134                     Robin Arnott       Austin, TX
135                Charlie Brumfield     Mesquite, TX
136           Lisabeth Sewell McCann       Austin, TX
137                Jenn Giles Kemper         Waco, TX
138                         GlocalMe       Dallas, TX
139                   Emergent Games      Rowlett, TX
140                        Tim Doyle       Austin, TX
141                     Rebecca Gray       Austin, TX
142               Red Republic Games       Austin, TX
143                Christopher Locke       Austin, TX
144                      Queen Games       Dallas, TX
145                     Jeremy Snead       Dallas, TX
146                Charlie Brumfield     Mesquite, TX
147                 Azpen Innovation        Plano, TX
148                       eoseek llc       Austin, TX
149             Bombshell Miniatures     Mckinney, TX
150                      GREG PABICH       Keller, TX
151                   SBARK dog toys       Dallas, TX
152                   Nicholas Vitek      Houston, TX
153                         PulsePet       Dallas, TX

[154 rows x 2 columns]

There are 154 inventors from Texas

### 3. How many people pledged more than 500 ?

In [282]:
run_query('SELECT SUM(Backers) FROM pledge_tiers WHERE "Pledge tiers" > 500')

   SUM(Backers)
0       89256.0

Close to 90,000 people have pledged more than 500$ !

### 4. Where do most of the inventors live ?

In [286]:
run_query('SELECT location, count(location) FROM most_backed GROUP BY location ORDER BY count(location) DESC LIMIT 5')

            Location  count(location)
0  San Francisco, CA              280
1    Los Angeles, CA              271
2       New York, NY              212
3        Seattle, WA              147
4         London, UK              132

Unsurprisingly, most of the creators are based out of San Francisco, California followed by Los Angeles, CA

### 5. Which are the top 5 most funded projects ?

In [287]:
run_query('SELECT * FROM most_backed ORDER BY "Amount Pledged" DESC LIMIT 5')

,Project ID,Amount Pledged,Blurb,Inventor ID,Category ID,Currency,Goal,Location,No. Backers,Title,URL
0,5,20338986.0,\nColor e-paper smartwatch with up to 7 days o...,1709,101,usd,500000.0,"Palo Alto, CA",78471,"Pebble Time - Awesome Smartwatch, No Compromises",/projects/597507018/pebble-time-awesome-smartw...
1,17,13285226.0,\nThe COOLEST is a portable party disguised as...,162,101,usd,50000.0,"Portland, OR",62642,COOLEST COOLER: 21st Century Cooler that's Act...,/projects/ryangrepper/coolest-cooler-21st-cent...
2,13,12779843.0,"\nTwo affordable, heart rate-enabled smartwatc...",1709,101,usd,1000000.0,"Redwood City, CA",66673,"Pebble 2, Time 2 + All-New Pebble Core",/projects/597507018/pebble-2-time-2-and-core-a...
3,11,10266845.0,\nPebble is a customizable watch. Download new...,1709,101,usd,100000.0,"Palo Alto, CA",68929,Pebble: E-Paper Watch for iPhone and Android,/projects/597507018/pebble-e-paper-watch-for-i...
4,21,9192055.0,"\nTRAVEL JACKET with built-in Neck Pillow, Eye...",3089,101,usd,20000.0,"Chicago, IL",44949,The World's Best TRAVEL JACKET with 15 Feature...,/projects/597538543/the-worlds-best-travel-jac...